export { default as PlayAreaIcon } from "./play-area";
export { default as GamesIcon } from "./games";
export { default as GymIcon } from "./gym";
export { default as BadmintonIcon } from "./badminton";
export { default as CommunityIcon } from './community';
export { default as GardenIcon} from './garden';
export { default as CctvIcon} from './cctv';
export { default as SecurityIcon} from './security';
export { default as RainwaterIcon} from './rainwater';
export { default as DrainageIcon} from './drainage';