import AuthProvider from '../../components/AuthProvider'

import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function CustomLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-red'>
        <AuthProvider>
        {children}
        </AuthProvider>
       
        </body>
    </html>
  )
}
